config/routes.rb
Rails.application.routes.draw do

get "/new" => "support_requests#new"

get "/support_requests" => "welcome#index", as: :support_requests

post "/support_requests" => "support_requests#create"

get "support_requests/:id/toggle_done" => "support_requests#toggle_done", as: :toggle_done_support_request

get "/support_requests/:id/edit" => "support_requests#edit", as: :edit_support_request

get "/support_requests/:id" => "support_requests#show", as: :support_request

patch "/support_requests/:id" => "support_requests#update"

delete "/support_requests/:id" => "support_requests#destroy"

 root "welcome#index"

end

app/models/support_request.rb
class SupportRequest < ActiveRecord::Base

# validation, callbacks, reordering with SQL, goes here
# this demands that the title exist before allowing this to enter the db
# here we can change the error messages that Rails gives
validates :name, presence: {message: "Please provide your name. "}

validates :email, presence: {message: "Please provide your email address. "}  

# validates :email, presence: {message: "Please provide your email address. "}, format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i


# code to set initial value of "done" to false. This is run every time a record is retrieved.
  after_initialize :defaults

  def defaults
    self.done = false if self.done.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController

  def new
    @support_request = SupportRequest.new
    
  end

  def create
    # the params from our form inclued a lot of just we don't want, we just want the question key value.
    # this will make a new support_request object for our db.
    # this is an instance variable so that we can access it's errors
    @support_request = SupportRequest.new support_request_params
    # this doens't yet put the object in the db, it has to be validated
    if @support_request.save
      redirect_to support_requests_path 
    else
      # show the form again with error, and use the layout called "special"
      render :new, layout: "special"
            # render :new
    end
  # render text: params
  end

  def show
    # take the user to their support request.
    @support_request = SupportRequest.find params[:id]
  end

  def edit
    @support_request = SupportRequest.find params[:id]
  end

  def update
    @support_request = SupportRequest.find params[:id]
    if @support_request.update support_request_params
      redirect_to support_requests_path
    else
      # using render here keeps the values the user put in. 
      # if you don't use render, it starts a different cycle, and all
      # the user's entries will be lost.
      render :edit
    end
  end

  def destroy
    @support_request = SupportRequest.find params[:id]
    @support_request.destroy
    redirect_to support_requests_path
  end

  def toggle_done
    # code to toggle the status of the clicked object
    @support_request = SupportRequest.find params[:id]
    # render text: params
    @support_request.done = !@support_request.done
    @support_request.save
    # then send user back to main page
    redirect_to support_requests_path

  end

  private
  def support_request_params
    # this is a security step. It only lets the variables through that we want.
    # this says, go to params, look for a key called question, and only allow the title and body values.
    support_request_params = params.require(:support_request).permit([:name, :email, :department, :message])
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
  #  this makes an object called @support_requests that is stuffed full of all 
    # the support requests, and orders them by whether  done is true or not
    
    @support_requests = SupportRequest.all.order(done: :desc)
  
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Looks like you forgot some information, try again please. </h1>
</body>
</html>

app/views/support_requests/_form.html.erb
<%# Here is my partial!!  %>

<%# form_for is a built-in view helper to generate a form. By default this will send the form to whatever the name is
pluralise it, and put _path on the end. in this case "questions_path" %>
<%= form_for @support_request do |s| %>

<%# label, text_field, these are all helpers from Rails   %>
  <%= s.label :name %>
  <%= s.text_field :name %>
  <br>
  <%= s.label :email %>
  <%= s.text_field :email %>
  <br>

  <%= s.radio_button(:department, "Sales") %>
  <%= s.label(:department_type, "Sales") %>

  <%= s.radio_button(:department, "Marketing") %>
  <%= s.label(:department_type, "Marketing") %>

  <%= s.radio_button(:department, "Technical") %>
  <%= s.label(:department_type, "Technical") %>

  <br>
  <%= s.label :message %>
  <%= s.text_area :message %>
  <br>
<%# create a hidden field to set the "done" value to false. broken %>
  <%# s.hidden_field :done,  value: "false" %>

  <%= s.submit %>
<% end %>

app/views/support_requests/edit.html.erb
<h1>Edit your ridiculous request!</h1>

<%# all the code that was here has been shifted to a partial nearby %>
<%= render "form" %>

<%# and add a way of deleting the request. %>
<%= link_to "Delete your request!! ", support_request_path(@support_request), method: :delete, data: {confirm: "are you sure??"} %>

app/views/support_requests/new.html.erb
<h1>This is the page to make a new support request!  </h1>

<p>Please enter your ridiculous request</p>

<%# all the code that was here has been shifted to a partial nearby %>
<%= render "form" %>

app/views/support_requests/show.html.erb
<h1>SHow and indvidual record here</h1>

<h1> Your Support request is from  <%= @support_request.name %> </h1>

<p> Your email is <%= @support_request.email %> </p>
<p> Your department is <%= @support_request.department %> </p>
<p> Your message is <%= @support_request.message %> </p>
<br>
<p> <%= link_to "Edit your SUpport Request", edit_support_request_path(@support_request) %></p>

app/views/welcome/index.html.erb
<h1>Support Requests </h1>

<a href="/new"> Click here to create a new support request</a>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>


  <% @support_requests.each do |individual_support_request| %>
  <tr>
    <td> <%= individual_support_request.name %> </td>
    <td> <a href="mailto:<%= individual_support_request.email %>?Subject=About your request. " ><%= individual_support_request.email %></a></td>
    <td> <%= individual_support_request.department %>   </td>
    <td> <%= individual_support_request.message %> </td>

    <td><%=  link_to "Edit", edit_support_request_path(individual_support_request) %></td>

    <td><%= link_to "Delete", support_request_path(individual_support_request), method: :delete, data: {confirm: "are you sure??"} %> </td>

    <%# link to path that will toggle the "done" status %>
     <td><%= link_to individual_support_request.done.to_s, toggle_done_support_request_path(individual_support_request) %>
     </td>
   </tr>   
  <% end %>
</table>